language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

addons:
  code_climate:
    repo_token: "Ih1cgvygqdyt8D9sxNUhuOaIatZl3OnfW"
    before_script:  # code coverage tool
      - curl -L https://codeclimate.com/github/ampaire/Api/code > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

# command to run tests
script: 
  - python3 -m pytest 

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - coveralls
  